'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ABLOCKALYPSE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ButtonMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HelpScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L49() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L49", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property L9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("L9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LevelScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LevelScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LoadScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MountainDew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MountainDew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Penguin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Penguin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
